[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "local text,disp_text,poker_hands,scoring_hand,non_loc_disp_text = G.FUNCS.get_poker_hand_info(G.play.cards)"
position = "after"
payload = '''
if next(poker_hands["Flush"]) ~= nil then
    play_sound("DansTweaks_flush", 1, 1)
end
'''
match_indent = true
times = 1